### PR TITLE
Suggested fixes

### LINKED ISSUE #140: missing definitions for zero
Hi there,
thanks for this work!

## System

- OS: linux (ubuntu 18.04)
- `ruby -v`: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
- `bundle -v`: Bundler version 2.1.4
- `bundle info arduino_ci`: arduino_ci (0.3.0)
- `g++ -v`: gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
- Arduino IDE version: 1.8.12
- `java -version`: openjdk version "1.8.0_252"

## Issue Summary
I'm testing a code that on arduino (physical board) mkr 1010 compiles with no issues, however with *arduino-ci* is failing with the following errors

```
Last command:  $ g++ -std=c++0x -o <my_path>/cronparser/unittest_test.cpp.bin -DARDUINO=100 -g -O1 -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address -D__SAMD21G18A__ -DARDUINO_SAMD_ZERO -I/var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino -I/var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/unittest -I<my_path>/cronparser /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/Arduino.cpp /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/Godmode.cpp /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/stdlib.cpp /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/unittest/ArduinoUnitTests.cpp <my_path>r/cronparser/cronparser.cpp /<my_path>/cronparser/test/test.cpp

In file included from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/avr/pgmspace.h:17:0,
                 from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/ArduinoDefines.h:3,
                 from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/Godmode.h:2,
                 from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/Arduino.cpp:1:
/var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/avr/io.h:623:6: warning: #warning "device type not defined" [-Wcpp]
 #    warning "device type not defined"
      ^~~~~~~
In file included from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/avr/pgmspace.h:17:0,
                 from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/ArduinoDefines.h:3,
                 from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/Godmode.h:2,
                 from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/Godmode.cpp:1:
/var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/avr/io.h:623:6: warning: #warning "device type not defined" [-Wcpp]
 #    warning "device type not defined"
      ^~~~~~~
In file included from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/Godmode.cpp:3:0:
/var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/SPI.h: In member function ‘uint16_t SPIClass::transfer16(uint16_t)’:
/var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/SPI.h:97:11: error: ‘SPCR’ was not declared in this scope
     if (!(SPCR & (1 << DORD))) {
           ^~~~
/var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/SPI.h:97:11: note: suggested alternative: ‘SPL’
     if (!(SPCR & (1 << DORD))) {
           ^~~~
           SPL
/var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/SPI.h:97:24: error: ‘DORD’ was not declared in this scope
     if (!(SPCR & (1 << DORD))) {
                        ^~~~
In file included from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/avr/pgmspace.h:17:0,
                 from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/unittest/Compare.h:2,
                 from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/unittest/Assertion.h:7,
                 from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/unittest/ArduinoUnitTests.h:4,
                 from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/unittest/ArduinoUnitTests.cpp:1:
/var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/avr/io.h:623:6: warning: #warning "device type not defined" [-Wcpp]
 #    warning "device type not defined"
      ^~~~~~~
In file included from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/avr/pgmspace.h:17:0,
                 from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/unittest/Compare.h:2,
                 from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/unittest/Assertion.h:7,
                 from /var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/unittest/ArduinoUnitTests.h:4,
                 from /mnt/Dati/Progetti/smart-water/cronparser/test/test.cpp:1:
/var/lib/gems/2.5.0/gems/arduino_ci-0.3.0/cpp/arduino/avr/io.h:623:6: warning: #warning "device type not defined" [-Wcpp]
 #    warning "device type not defined"
      ^~~~~~~
```

Works on the following platforms:
- uno
- due
- mega

## Arduino or Unit Test Code, Illustrating the Problem
The issue seem to be related to the import of `WString.h`. My code uses nothing strictly related to the SAMD processor, indeed here is the hole import list

```c++
#include <time.h>
#include <string.h>
#include <WString.h>
```

Working `.arduino-ci.yaml`
```yaml
compile:
  libraries: ~
  platforms:
    - uno
    - due
    - mega2560
    - leonardo
    # - zero

unittest:
  libraries: ~
  platforms:
    - uno
    - due
    - mega2560
    - leonardo
    # - zero
```

broken `.arduino-ci.yaml`
```yaml
compile:
  libraries: ~
  platforms:
    - uno
    - due
    - mega2560
    - leonardo
    - zero

unittest:
  libraries: ~
  platforms:
    - uno
    - due
    - mega2560
    - leonardo
    - zero
```

## Arduino Architecture(s) Affected

zero, as far as i know.

Thanks!

### LINKED ISSUE #166: Support for EEPROM
As @per1234 explained [here](https://github.com/Arduino-CI/arduino_ci/issues/150#issuecomment-692444392), [SPI](https://www.arduino.cc/en/Reference/SPI) and [Wire](https://www.arduino.cc/en/Reference/wire) are [platform bundled libraries](https://arduino.github.io/arduino-cli/latest/platform-specification/#platform-bundled-libraries) and I see that mocks are included for them in `arduino_ci`. Is [EEPROM](https://www.arduino.cc/en/Reference/EEPROM) similar? Should it be part of the base or an add-on like [LiquidCrystal](https://github.com/Arduino-CI/LiquidCrystal)?

### LINKED ISSUE #168: Multiple definition of 'main' when including a library with tests
## System

- OS: Linux
- `ruby -v`: ruby 2.3.1p112
- `bundle -v`: Bundler version 2.1.4
- `bundle info arduino_ci`: arduino_ci (0.3.0)
- `g++ -v`: gcc version 5.4.0 20160609
- URL of your Arduino project: https://github.com/rosogon/arduino_ci_two_libraries

## Issue Summary

If libB depends on libA, both with arduino_ci tests, trying to run the unit tests on libB will raise the error "multiple definition of main". This happens because [cpp_files_libraries](https://github.com/Arduino-CI/arduino_ci/blob/master/lib/arduino_ci/cpp_library.rb#L188) returns the whole tree of the referenced library (libA in the example), not removing the files in test/.

Con: Skipping those files can break libraries containing files in test/ (which are needed to use the library). Weird, but could happen.

## Arduino or Unit Test Code, Illustrating the Problem

The following repo illustratres the example: https://github.com/rosogon/arduino_ci_two_libraries

```
libB $ bundle exec arduino_ci_remote.rb --skip-compilation
Located Arduino binary...                     /home/roman/arduino_ci_ide/arduino
[...]
Requested unittest platform 'uno' is defined in 'platforms' YML...             ✓
Using pre-existing library...                                               libA
Unit testing test.cpp with g++... 

Last command:  $ g++ -std=c++0x -o /home/roman/romanfiles/projects/Arduino/arduino_ci_two_libraries/libB/unittest_test.cpp.bin -DARDUINO=100 -g -O1 -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address -D__AVR_ATmega328P__ -I/home/roman/romanfiles/projects/Arduino/arduino_ci_two_libraries/.bundle/ruby/2.3.0/gems/arduino_ci-0.3.0/cpp/arduino -I/home/roman/romanfiles/projects/Arduino/arduino_ci_two_libraries/.bundle/ruby/2.3.0/gems/arduino_ci-0.3.0/cpp/unittest -I/home/roman/projects/Arduino/libraries/libA /home/roman/romanfiles/projects/Arduino/arduino_ci_two_libraries/.bundle/ruby/2.3.0/gems/arduino_ci-0.3.0/cpp/arduino/Arduino.cpp /home/roman/romanfiles/projects/Arduino/arduino_ci_two_libraries/.bundle/ruby/2.3.0/gems/arduino_ci-0.3.0/cpp/arduino/Godmode.cpp /home/roman/romanfiles/projects/Arduino/arduino_ci_two_libraries/.bundle/ruby/2.3.0/gems/arduino_ci-0.3.0/cpp/arduino/stdlib.cpp /home/roman/romanfiles/projects/Arduino/arduino_ci_two_libraries/.bundle/ruby/2.3.0/gems/arduino_ci-0.3.0/cpp/unittest/ArduinoUnitTests.cpp /home/roman/romanfiles/projects/Arduino/arduino_ci_two_libraries/libA/test/test.cpp /home/roman/romanfiles/projects/Arduino/arduino_ci_two_libraries/libB/test/test.cpp                                                                                                                         

/tmp/ccFO4mjB.o: In function `std::basic_ostream<char, std::char_traits<char> >& std::flush<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)':
/home/roman/romanfiles/projects/Arduino/arduino_ci_two_libraries/.bundle/ruby/2.3.0/gems/arduino_ci-0.3.0/cpp/unittest/ArduinoUnitTests.h:149: multiple definition of `main'
/tmp/ccudL6dM.o:/home/roman/romanfiles/projects/Arduino/arduino_ci_two_libraries/libA/test/test.cpp:10: first defined here
collect2: error: ld returned 1 exit status
...Unit testing test.cpp with g++                                              ✗
Skipping compilation of examples...                as requested via command line
Failures: 1
```

### LINKED ISSUE #175: Confusion over `skip-compilation` option
As described in `REFERENCE.md`, this framework will (_compile_ and) run all the code in the `test` directory on the developer's desktop/laptop against the _mock_ Arduino board. Then, as a separate task an attempt is made to build everything in the `examples` directory using the Arduino IDE (which has different includes and a different compiler) so as to avoid later surprises due to the different build environment and target. These tasks are very reasonable and distinct, but I was confused by the names.

I spent a lot of time fiddling with test code to get the unit tests to _compile_ and run and the idea that I'm running the unit tests without compiling seems very odd. Now that I'm understanding better I wonder if "compilation of examples" would be a better phrase (even though it is more verbose). 

So, the command line option `--skip-compilation` would probably remain but would be deprecated in favor of `--skip-compilation-of-examples` or simply `--skip-examples` (more analogous to `--skip-unittests`).

### LINKED ISSUE #187: Fix _SFR_IO8 macro to avoid "cannot take the address of an rvalue"
## Issue Summary 

see https://github.com/Arduino-CI/SD/issues/2

```
error: cannot take the address of an rvalue of type 'int'
  {&DDRE, &PINE, &PORTE, 0},  // E0  0
   ^~~~~
```

[Working theory](https://github.com/Arduino-CI/SD/issues/2#issuecomment-716266934) is that this is caused by a badly formed macro. 

https://github.com/Arduino-CI/arduino_ci/blob/master/cpp/arduino/avr/io.h#L99

```diff
- #define _SFR_IO8(io_addr) (io_addr) // this macro is all we need from the sfr file 
+ #define _MMIO_BYTE(mem_addr) (*(volatile uint8_t *)(mem_addr))
+ #define _SFR_IO8(io_addr) _MMIO_BYTE((io_addr) + __SFR_OFFSET)
```

Will see if `volatile` is sufficient to fix

### LINKED ISSUE #196: `_SFR_IO8` no longer visible after definition moved to a new file
As part of `8180efbf09a8337dcb89b6a7c8dccf97f26bb627` in `2020-10-16_suggestions` the definition of `_SFR_IO8` was moved from `cpp/arduino/arv/io.h` to `cpp/arduino/Arduino.h`. Unfortunately, this macro is referenced from `cpp/arduino/SPI.h` and now is not found. 

```text
Run bundle exec arduino_ci_remote.rb
Located Arduino binary...                    /home/runner/arduino_ci_ide/arduino
The set of compilers (1) isn't empty...                                        ✓
Checking g++ version... 
    Using built-in specs.
    COLLECT_GCC=g++
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
    OFFLOAD_TARGET_NAMES=nvptx-none
    OFFLOAD_TARGET_DEFAULT=1
    Target: x86_64-linux-gnu
    Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
    Thread model: posix
    gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
...Checking g++ version                                                        ✓
libasan availability for g++...                                             true
Requested unittest platform 'mega2560' is defined in 'platforms' YML...        ✓
Library conforms to Arduino library specification...                         1.5
Using pre-existing library...                                      LiquidCrystal
Installing aux library 'RTClib'...                                             ✓
Unit testing Blink.cpp with g++... 

Last command:  $ g++ -std=c++0x -o /home/runner/work/TankControllerLib/TankControllerLib/unittest_Blink.cpp.bin -DARDUINO=100 -D__AVR__ -g -O1 -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address -D__AVR_ATmega2560__ -DARDUINO_CI -I/home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/arduino -I/home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/unittest -I/home/runner/work/TankControllerLib/TankControllerLib/src -I/home/runner/work/TankControllerLib/TankControllerLib/src/Devices -I/home/runner/work/TankControllerLib/TankControllerLib/src/UIState -I/home/runner/Arduino/libraries/LiquidCrystal/src -I/home/runner/Arduino/libraries/RTClib /home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/arduino/Arduino.cpp /home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/arduino/Godmode.cpp /home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/arduino/stdlib.cpp /home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/unittest/ArduinoUnitTests.cpp /home/runner/work/TankControllerLib/TankControllerLib/src/TankControllerLib.cpp /home/runner/work/TankControllerLib/TankControllerLib/src/Devices/LiquidCrystal_TC.cpp /home/runner/work/TankControllerLib/TankControllerLib/src/UIState/MainMenu.cpp /home/runner/Arduino/libraries/LiquidCrystal/src/LiquidCrystal.cpp /home/runner/Arduino/libraries/LiquidCrystal/src/LiquidCrystal_CI.cpp /home/runner/Arduino/libraries/RTClib/RTClib.cpp /home/runner/work/TankControllerLib/TankControllerLib/test/Blink.cpp

In file included from /home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/arduino/avr/iom2560.h:38:0,
                 from /home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/arduino/avr/io.h:172,
                 from /home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/arduino/avr/pgmspace.h:17,
                 from /home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/arduino/ArduinoDefines.h:3,
                 from /home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/arduino/Godmode.h:2,
                 from /home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/arduino/Godmode.cpp:1:
/home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/arduino/SPI.h: In member function ‘uint16_t SPIClass::transfer16(uint16_t)’:
/home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/arduino/avr/iomxx0_1.h:387:17: error: ‘_SFR_IO8’ was not declared in this scope
 #define SPCR    _SFR_IO8(0x2C)
                 ^
/home/runner/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/arduino_ci-8180efbf09a8/cpp/arduino/SPI.h:97:11: note: in expansion of macro ‘SPCR’
     if (!(SPCR & (1 << DORD))) {
           ^~~~
...Unit testing Blink.cpp with g++                                             ✗
```

### PR DESCRIPTION
**Pull request by ianfixes**
### Trying it out
You can test this beta of the gem directly from github by putting this in your `Gemfile`:

```ruby
gem 'arduino_ci', git: 'https://github.com/ianfixes/arduino_ci.git', branch: '2020-10-16_suggestions'
```

### Added
- `arduino_ci_remote.rb` CLI switch `--skip-examples-compilation`
- `CppLibrary.header_files` to find header files
- `LibraryProperties` to read metadata from Arduino libraries
- `CppLibrary.library_properties_path`, `CppLibrary.library_properties?`, `CppLibrary.library_properties` to expose library properties of a Cpp library
- `CppLibrary.arduino_library_dependencies` to list the dependent libraries specified by the library.properties file

### Changed
- `CppLibrary` functions returning C++ header or code files now respect the 1.0/1.5 library specification

### Deprecated
- `arduino_ci_remote.rb` CLI switch `--skip-compilation`

### Fixed
- Don't define `ostream& operator<<(nullptr_t)` if already defined by Apple
- `CppLibrary.in_tests_dir?` no longer produces an error if there is no tests directory
- The definition of the `_SFR_IO8` macro no longer produces errors about rvalues

* See CHANGELOG.md for more

## Issues Fixed

* Fixes #175
* Fixes #168
* Fixes #187
* Fixes #196 
* Fixes #140
* Fixes #166

### CODE REVIEW

File: cpp/arduino/Arduino.h [hunk 1]
```diff
@@ -5,6 +5,15 @@ Mock Arduino.h library.
 Where possible, variable names from the Arduino library are used to avoid conflicts
 
 */
+
+// hardware mocks
+volatile long long __ARDUINO_CI_SFR_MOCK[1024];
```
Comment (jgfoster) [inline cpp/arduino/Arduino.h:10]: I believe that if you defined a variable in a header file then it gets defined every time that header file is included and you get multiple definitions. Instead, if you define it as `extern` in the header and then put it in a `.cpp` file, it will be created only once.

File: cpp/arduino/Arduino.h [hunk 2]
```diff
@@ -5,6 +5,15 @@ Mock Arduino.h library.
...
+#define _SFR_IO8(io_addr) (*(volatile uint8_t *)(__ARDUINO_CI_SFR_MOCK + io_addr)) // this macro is all we need from the sfr file
+#define _SFR_IO16(io_addr) (*(volatile uint16_t *)(__ARDUINO_CI_SFR_MOCK + io_addr)) // this macro is all we need from the sfr file
+#define _SFR_MEM8(io_addr) (*(volatile uint8_t *)(__ARDUINO_CI_SFR_MOCK + io_addr)) // this macro is all we need from the sfr file
+#define _SFR_MEM16(io_addr) (*(volatile uint16_t *)(__ARDUINO_CI_SFR_MOCK + io_addr)) // this macro is all we need from the sfr file
+#define _SFR_MEM32(io_addr) (*(volatile uint32_t *)(__ARDUINO_CI_SFR_MOCK + io_addr)) // this macro is all we need from the sfr file
```
Comment (matthijskooijman) [inline cpp/arduino/Arduino.h:15]: I would leave this stuff in `io.h`, which is where they are used and what any other code that (god knows why) uses them would expect them.

**Review by matthijskooijman — COMMENTED** [review]
Just had a look at the `io.h` stuff, that (the last commit, the first one that "fixes" `_SFR_IO8` only makes it broken in a different way) looks pretty much like what I had in mind for the first part of https://github.com/Arduino-CI/arduino_ci/issues/193#issuecomment-723018149

File: cpp/arduino/Arduino.h (hunk 2 above)
Comment (jgfoster) [reply cpp/arduino/Arduino.h:15]: I'm looking at this and right now the issue is that `SampleProjects/TestSomething/test/godmode.cpp` fails the `spi` tests due to bytes being in the wrong order.

Comment (matthijskooijman) [reply cpp/arduino/Arduino.h:15]: I'm not sure what you mean here? If you move this to io.h, that makes the tests fail? But not because of include order or something like that, but "byte order"?

File: cpp/arduino/Arduino.h (hunk 1 above)
Comment (matthijskooijman) [reply cpp/arduino/Arduino.h:10]: Also, I think this should declare a `uin8_t*` array, rather than a `long long` array. If not, I think that each byte in the original "address space" (i.e. offsets passed to `_SFR_IOx` macros) end up in different `long long` entries in this array, so multi-byte values do not map properly anymore (i.e. `ADC` maps to either `ADCH` or `ADCL` (dunno which off-hand), rather than being a combination of both).

Also, the current code violates strict type aliasing (accessing a `longlong[]` through a pointer of a different type is not allowed), which means the compiler *might* mess up optimizations regarding this array. I was hoping that making it a `uint8_t` array would solve this, but it seems this only works the other way around (accessing an arbitrary type through a `uint8_t*`). So maybe this needs access through a union to make it explicit to the compiler what's happening...

File: cpp/arduino/Arduino.h (hunk 2 above)
Comment (jgfoster) [reply cpp/arduino/Arduino.h:15]: Just for completeness, this conversation is continuing in #201.

**Comment by ianfixes** [comment]
Reverting 8180efb as per this https://github.com/Arduino-CI/arduino_ci/issues/196#issuecomment-723476602
